#!/usr/bin/env bash
        
echo 'Nmap version 7.80 ( https://nmap.org  )
Platform: x86_64-apple-darwin19.5.0
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1g nmap-libssh2-1.8.2 libz-1.2.11 nmap-libpcre-7.6 libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: kqueue poll select'
