kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
nodes:
- role: control-plane
  image: kindest/node:v1.17.2
- role: worker
  image: kindest/node:v1.17.2
- role: worker
  image: kindest/node:v1.17.2
